module.exports = { 
  id: 671,
  suite_id: 1,
  name: 'Automated test run - Apr 16 2019, 16:26',
  description: null,
  milestone_id: null,
  assignedto_id: null,
  include_all: true,
  is_completed: false,
  completed_on: null,
  config: null,
  config_ids: [],
  passed_count: 0,
  blocked_count: 0,
  untested_count: 72,
  retest_count: 0,
  failed_count: 0,
  custom_status1_count: 0,
  custom_status2_count: 0,
  custom_status3_count: 0,
  custom_status4_count: 0,
  custom_status5_count: 0,
  custom_status6_count: 0,
  custom_status7_count: 0,
  project_id: 1,
  plan_id: null,
  created_on: 1555417566,
  created_by: 1,
  url: 'https://stepan.testrail.io/index.php?/runs/view/671'
};
